In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

In [2]:
data = pd.read_csv("./CSV/Boston.csv")
data.head()

crim    zn  indus    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [3]:
x = data.iloc[:,:12]
y = data.iloc[:,12]

In [4]:
model = LinearRegression()
model

LinearRegression()

In [5]:
cvals = -cross_val_score(model,x,y,cv = 5 ,scoring='mean_squared_error')
cvals #this is not valid 

InvalidParameterError: The 'scoring' parameter of cross_val_score must be a str among {'precision_macro', 'adjusted_rand_score', 'precision_micro', 'jaccard', 'jaccard_micro', 'f1_macro', 'average_precision', 'recall_micro', 'neg_root_mean_squared_log_error', 'positive_likelihood_ratio', 'neg_mean_squared_error', 'max_error', 'adjusted_mutual_info_score', 'neg_negative_likelihood_ratio', 'rand_score', 'homogeneity_score', 'normalized_mutual_info_score', 'roc_auc', 'precision_weighted', 'fowlkes_mallows_score', 'f1', 'precision_samples', 'neg_root_mean_squared_error', 'precision', 'jaccard_samples', 'balanced_accuracy', 'neg_median_absolute_error', 'r2', 'roc_auc_ovr', 'neg_brier_score', 'roc_auc_ovo', 'neg_mean_gamma_deviance', 'top_k_accuracy', 'accuracy', 'f1_micro', 'neg_mean_absolute_error', 'neg_mean_poisson_deviance', 'jaccard_weighted', 'v_measure_score', 'completeness_score', 'neg_mean_absolute_percentage_error', 'roc_auc_ovr_weighted', 'recall_weighted', 'matthews_corrcoef', 'mutual_info_score', 'neg_log_loss', 'jaccard_macro', 'f1_samples', 'recall_samples', 'neg_mean_squared_log_error', 'f1_weighted', 'recall', 'roc_auc_ovo_weighted', 'recall_macro', 'explained_variance'}, a callable or None. Got 'mean_squared_error' instead.

In [13]:
cvals = -cross_val_score(model,x,y,cv = 5 ,scoring='neg_mean_squared_error')
cvals
#scikit learn prefers higher scores are better.
#MSE is an error metric where lower is better
#This gives a higher value of negative value. That mean negative form of negative error.

array([12.6721495 , 24.28442268, 27.83877583, 82.08494898, 36.50537454])

In [15]:
RMSE = np.sqrt(cvals)
RMSE

array([3.55979627, 4.92792276, 5.27624638, 9.06007445, 6.04196777])

In [17]:
np.mean(RMSE)

5.7732015243570975

In [19]:
cvals_r2 = cross_val_score(model,x,y,cv = 5 ,scoring='r2')
cvals_r2  

array([ 0.63306565,  0.73324595,  0.65239421,  0.06415214, -0.37298554])

In [21]:
np.mean(cvals_r2)

0.34197447998424085

In [23]:
model.fit(x,y)

LinearRegression()

TypeError: LinearModel.predict() missing 1 required positional argument: 'X'