In [1]:
import numpy as np

In [2]:
np.sqrt(25)

5.0

In [3]:
np.power(3,2)

9

In [4]:
np.sin(30)

-0.9880316240928618

In [5]:
np.log(100)

4.605170185988092

In [6]:
np.exp(0)

1.0

In [7]:
L = [10,20,30,40,"ABC"]
a = np.array(L)
a

array(['10', '20', '30', '40', 'ABC'], dtype='<U11')

In [8]:
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [9]:
b.shape

(3, 3)

In [10]:
a.ndim #number of dimensions


1

In [11]:
b.ndim

2

In [12]:
print(b[0,1])

20


In [13]:
print(b[0,1])

20


In [14]:
print(b[:3]) # print rows in 2d array

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [15]:
print(b[::2])

[[10 20 30]
 [70 80 90]]


In [16]:
b.dtype

dtype('int32')

In [17]:
original_array = np.array([1,2,3])
view_array = original_array[:2] # get only certain values 
#this taking only the reference address

original_array[0] = 100
print(view_array)

[100   2]


In [18]:
original_array = np.array([10,20,30])
copy_array = original_array[:2].copy()

original_array[0] = 100;

print(original_array)
print(copy_array)

[100  20  30]
[10 20]


In [19]:
array1 = np.array([10,20,30])
array2 = np.array([40,50,60])

result = np.concatenate((array1,array2)) #combine both arrays

print(result)

result2 = np.append(array1 , array2)
print(result2)


[10 20 30 40 50 60]
[10 20 30 40 50 60]


In [20]:
result3 = np.add(array1,array2) #add both arrays and get new array
print(result3)

result4 = np.subtract(array1,array2) #substract both arrays and get new array
print(result4)

[50 70 90]
[-30 -30 -30]


In [21]:
#create a 1D array
array = np.array([1,2,3,4,5,6,7,8,9])

#split the array into 3 parts
split_array = np.array_split(array,3)
print("Split Array into 3 parts : " , split_array)


for i, part in enumerate(split_array):
    print(f"Part {i+1} : {part}")

Split Array into 3 parts :  [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
Part 1 : [1 2 3]
Part 2 : [4 5 6]
Part 3 : [7 8 9]


In [22]:
array = np.array([10,20,30,40,50,60,70,80,90])

#split the array at specified indices
split_array = np.array_split(array , [2,5,6]) 
# 0-1 --> 1-4 --> 5-6
# [0,1] --> [2,3,4] --> [5] --> [6,7,8]
for i, part in enumerate(split_array):
    print(f"Part {i+1} : {part}")

Part 1 : [10 20]
Part 2 : [30 40 50]
Part 3 : [60]
Part 4 : [70 80 90]


In [23]:
array_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

#split the 2d array into 2 parts along the rows (axis = 0)

split_2d_array = np.array_split(array_2d , 2 , axis = 0) 
# we can remove axis but it takes default axis = 0
# split_2d_array = np.array_split(array_2d , 2)
print("\nSplit 2D array into 2 parts along the rows : ")
for i, part in enumerate(split_2d_array):
    print(f"Part {i+1} :\n {part}")


Split 2D array into 2 parts along the rows : 
Part 1 :
 [[1 2 3 4]
 [5 6 7 8]]
Part 2 :
 [[ 9 10 11 12]]


In [24]:
array_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

#split the 2d array into 2 parts along the colomns (axis = 0)

split_2d_array = np.array_split(array_2d , 2 , axis = 1)
print("\nSplit 2D array into 2 parts along the rows : ")
for i, part in enumerate(split_2d_array):
    print(f"Part {i+1} :\n {part}")


Split 2D array into 2 parts along the rows : 
Part 1 :
 [[ 1  2]
 [ 5  6]
 [ 9 10]]
Part 2 :
 [[ 3  4]
 [ 7  8]
 [11 12]]


In [25]:
array = np.array([1,2,3,4,5,3,7,3,9,3]);
result = np.where(array == 3)
print(result)
print(result[0])
print(len(result[0]))

(array([2, 5, 7, 9], dtype=int64),)
[2 5 7 9]
4


In [26]:
array = np.array([1,2,3,7,6,4,2])
sorted_array = np.sort(array)
print(sorted_array)
print(array)
array.sort()
print(array)

[1 2 2 3 4 6 7]
[1 2 3 7 6 4 2]
[1 2 2 3 4 6 7]


In [27]:
a = np.array([1,2,3,4,5,43,3,32,23,2,3,4])
print(a.shape)

(12,)


In [51]:
a = a.reshape(4,3) # we can reshape array 
a

array([[ 1,  2,  3],
       [ 4,  5, 43],
       [ 3, 32, 23],
       [ 2,  3,  4]])

In [53]:
a[3,2]

4

In [55]:
a[1:3,1:]

array([[ 5, 43],
       [32, 23]])

In [57]:
a[[1,3],[0,2]]

array([4, 4])

In [59]:
a[a>5]

array([43, 32, 23])

In [61]:
a[:,1][a[:,1] > 2]

array([ 5, 32,  3])

In [ ]:
a[1:3,1:]   # takes rows 1 , 2 and take colms 1 ,2 

In [ ]:
a.sum() # get summation of all numbers in array

In [ ]:
a.min() # get minimum value

In [ ]:
a.max()

In [ ]:
a.mean()

In [ ]:
a * 10

In [ ]:
b = np.array([12,23,43,23,56,2,3,4,324,65,76,43])
b = b.reshape(4,3)

In [ ]:
a + b # we cant concatinate before make it into same dimension 

In [ ]:
b

In [ ]:
a

In [ ]:
a * b

In [ ]:
b = b.reshape(3,4)
result = a.dot(b)
result

In [ ]:
data = np.random.randn(100)
data

In [ ]:
import numpy as np

# Generate a 5x2 array of random floats in [0.0, 1.0) , np.random.random(size)
random_floats = np.random.random((5, 2))
print("Random floats:\n", random_floats)

# Generate a 5x2 array of random floats in [0.0, 1.0) using rand , np.random.rand(d0, d1, ..., dn)
random_floats_rand = np.random.rand(5, 2, 3)
print("\nRandom floats using rand:\n", random_floats_rand)

# Generate a 5x2 array of random floats from a normal distribution
random_normals = np.random.randn(5, 2)
print("\nRandom normals:\n", random_normals)

# Generate a 5x2 array of random integers from 0 to 9
random_ints = np.random.randint(0, 10, (5, 2))
print("\nRandom integers:\n", random_ints)

# Generate a 5x2 array of random samples from a given 1-D array
random_choice = np.random.choice([1, 2, 3, 4, 5], size=(5, 2))
print("\nRandom choice:\n", random_choice)

# Generate a 5x2 array of random floats in [1.0, 3.0)
random_uniforms = np.random.uniform(1.0, 3.0, (5, 2))
print("\nRandom uniforms:\n", random_uniforms)

# Generate a 5x2 array of random samples from a binomial distribution
random_binomials = np.random.binomial(n=10, p=0.5, size=(5, 2))
print("\nRandom binomials:\n", random_binomials)

# Generate a 5x2 array of random samples from a beta distribution
random_betas = np.random.beta(a=2.0, b=5.0, size=(5, 2))
print("\nRandom betas:\n", random_betas)

# Generate a 5x2 array of random samples from a Poisson distribution
random_poissons = np.random.poisson(lam=3.0, size=(5, 2))
print("\nRandom poissons:\n", random_poissons)

In [ ]:
normalized_data = (data - np.mean(data)) / np.std(data)
print("Normalized data : \n",normalized_data)

In [ ]:
data = np.random.normal(size = 20 , loc = 50 , scale = 0.2) #loc = location parameter
print(data) 

In [ ]:
array = np.arange(21)
array

In [ ]:
even_mask = array % 2 == 0
even_numbers = array[even_mask]

print("Even Numbers ",even_numbers)

In [ ]:
arr = np.array([1.32473,23.34234,42.2342,3.23432])

rounded_array = np.round(arr,decimals = 2)

print(rounded_array)

arr = np.array([2.9 , -2.9 , 2.9 , -2.1])

fixed_arr = np.fix(arr)

print(fixed_arr)