In [1]:
import numpy as np

In [2]:
np.sqrt(25)

5.0

In [3]:
np.power(3,2)

9

In [4]:
np.sin(30)

-0.9880316240928618

In [5]:
np.log(100)

4.605170185988092

In [6]:
np.exp(0)

1.0

In [7]:
L = [10,20,30,40,"ABC"]
a = np.array(L)
a

array(['10', '20', '30', '40', 'ABC'], dtype='<U11')

In [8]:
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [9]:
b.shape

(3, 3)

In [10]:
a.ndim #number of dimensions


1

In [11]:
b.ndim

2

In [12]:
print(b[0,1])

20


In [13]:
print(b[0,1])

20


In [14]:
print(b[:3]) # print rows in 2d array

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [15]:
print(b[::2])

[[10 20 30]
 [70 80 90]]


In [16]:
b.dtype

dtype('int32')

In [17]:
original_array = np.array([1,2,3])
view_array = original_array[:2] # get only certain values 
#this taking only the reference address

original_array[0] = 100
print(view_array)

[100   2]


In [18]:
original_array = np.array([10,20,30])
copy_array = original_array[:2].copy()

original_array[0] = 100;

print(original_array)
print(copy_array)

[100  20  30]
[10 20]


In [19]:
array1 = np.array([10,20,30])
array2 = np.array([40,50,60])

result = np.concatenate((array1,array2)) #combine both arrays

print(result)

result2 = np.append(array1 , array2)
print(result2)


[10 20 30 40 50 60]
[10 20 30 40 50 60]


In [20]:
result3 = np.add(array1,array2) #add both arrays and get new array
print(result3)

result4 = np.subtract(array1,array2) #substract both arrays and get new array
print(result4)

[50 70 90]
[-30 -30 -30]


In [21]:
#create a 1D array
array = np.array([1,2,3,4,5,6,7,8,9])

#split the array into 3 parts
split_array = np.array_split(array,3)
print("Split Array into 3 parts : " , split_array)


for i, part in enumerate(split_array):
    print(f"Part {i+1} : {part}")

Split Array into 3 parts :  [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
Part 1 : [1 2 3]
Part 2 : [4 5 6]
Part 3 : [7 8 9]


In [22]:
array = np.array([10,20,30,40,50,60,70,80,90])

#split the array at specified indices
split_array = np.array_split(array , [2,5,6]) 
# 0-1 --> 1-4 --> 5-6
# [0,1] --> [2,3,4] --> [5] --> [6,7,8]
for i, part in enumerate(split_array):
    print(f"Part {i+1} : {part}")

Part 1 : [10 20]
Part 2 : [30 40 50]
Part 3 : [60]
Part 4 : [70 80 90]


In [23]:
array_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

#split the 2d array into 2 parts along the rows (axis = 0)

split_2d_array = np.array_split(array_2d , 2 , axis = 0) 
# we can remove axis but it takes default axis = 0
# split_2d_array = np.array_split(array_2d , 2)
print("\nSplit 2D array into 2 parts along the rows : ")
for i, part in enumerate(split_2d_array):
    print(f"Part {i+1} :\n {part}")


Split 2D array into 2 parts along the rows : 
Part 1 :
 [[1 2 3 4]
 [5 6 7 8]]
Part 2 :
 [[ 9 10 11 12]]


In [24]:
array_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

#split the 2d array into 2 parts along the colomns (axis = 0)

split_2d_array = np.array_split(array_2d , 2 , axis = 1)
print("\nSplit 2D array into 2 parts along the rows : ")
for i, part in enumerate(split_2d_array):
    print(f"Part {i+1} :\n {part}")


Split 2D array into 2 parts along the rows : 
Part 1 :
 [[ 1  2]
 [ 5  6]
 [ 9 10]]
Part 2 :
 [[ 3  4]
 [ 7  8]
 [11 12]]


In [25]:
array = np.array([1,2,3,4,5,3,7,3,9,3]);
result = np.where(array == 3)
print(result)
print(result[0])
print(len(result[0]))

(array([2, 5, 7, 9], dtype=int64),)
[2 5 7 9]
4


In [26]:
array = np.array([1,2,3,7,6,4,2])
sorted_array = np.sort(array)
print(sorted_array)
print(array)
array.sort()
print(array)

[1 2 2 3 4 6 7]
[1 2 3 7 6 4 2]
[1 2 2 3 4 6 7]


In [27]:
a = np.array([1,2,3,4,5,43,3,32,23,2,3,4])
print(a.shape)

(12,)


In [92]:
a.reshape(4,3) # we can reshape array 
a

array([[ 1,  2,  3],
       [ 4,  5, 43],
       [ 3, 32, 23],
       [ 2,  3,  4]])

In [94]:
a[3,2]

4

In [96]:
a[1:3,1:]   # takes rows 1 , 2 and take colms 1 ,2 

array([[ 5, 43],
       [32, 23]])

In [98]:
a.sum() # get summation of all numbers in array

125

In [100]:
a.min() # get minimum value

1

In [80]:
a.max()

43

In [82]:
a.mean()

10.416666666666666

In [84]:
a * 10

array([[ 10,  20,  30],
       [ 40,  50, 430],
       [ 30, 320, 230],
       [ 20,  30,  40]])

In [88]:
b = np.array([12,23,43,23,56,2,3,4,324,65,76,43])
b = b.reshape(4,3)

In [102]:
a + b # we cant concatinate before make it into same dimension 

array([[ 13,  25,  46],
       [ 27,  61,  45],
       [  6,  36, 347],
       [ 67,  79,  47]])

In [113]:
b

array([[ 12,  23,  43],
       [ 23,  56,   2],
       [  3,   4, 324],
       [ 65,  76,  43]])

In [115]:
a

array([[ 1,  2,  3],
       [ 4,  5, 43],
       [ 3, 32, 23],
       [ 2,  3,  4]])

In [117]:
a * b

array([[  12,   46,  129],
       [  92,  280,   86],
       [   9,  128, 7452],
       [ 130,  228,  172]])

In [121]:
b = b.reshape(3,4)
result = a.dot(b)
result

array([[ 1096,   222,   277,   160],
       [14260,  2897,  3455,  1961],
       [ 9280,  1628,  1973,  1186],
       [ 1488,   312,   399,   230]])

In [131]:
data = np.random.randn(100)
data

array([ 1.46907865,  1.46979043, -1.16508465,  1.02707518,  0.23359037,
       -0.68607119, -1.87421294,  0.36423236, -0.85498321, -0.67600419,
        0.66816871, -0.98210102,  0.04076212, -0.59465655,  0.81723842,
        0.37188208,  0.07499651,  1.75234223,  1.39897163, -0.36298031,
        0.02327155,  0.94939977,  1.62127682, -0.98305489,  0.23144838,
       -0.56415117,  0.7857072 , -0.72754774, -0.44185482,  0.67239088,
       -0.61925424,  1.6064661 ,  0.77162781,  0.88938931, -1.03413836,
        1.3387397 , -0.49230103,  0.7510678 , -0.36919914, -0.83811033,
        1.00485985,  2.24787962,  1.01714768, -0.91341541,  0.18182285,
        0.03731996, -0.29347963, -0.98322995, -0.09631636,  0.58574845,
       -0.63409431,  0.2928295 , -1.92010371, -2.25415786, -0.23523204,
       -0.42928108, -0.04502848,  0.43593512,  0.19328509,  0.14509232,
       -0.61212977, -0.57355815,  0.8187677 , -0.36133483,  1.39740315,
       -0.94010992, -1.41100528,  0.49171113,  1.11480403,  0.49

In [137]:
import numpy as np

# Generate a 5x2 array of random floats in [0.0, 1.0) , np.random.random(size)
random_floats = np.random.random((5, 2))
print("Random floats:\n", random_floats)

# Generate a 5x2 array of random floats in [0.0, 1.0) using rand , np.random.rand(d0, d1, ..., dn)
random_floats_rand = np.random.rand(5, 2, 3)
print("\nRandom floats using rand:\n", random_floats_rand)

# Generate a 5x2 array of random floats from a normal distribution
random_normals = np.random.randn(5, 2)
print("\nRandom normals:\n", random_normals)

# Generate a 5x2 array of random integers from 0 to 9
random_ints = np.random.randint(0, 10, (5, 2))
print("\nRandom integers:\n", random_ints)

# Generate a 5x2 array of random samples from a given 1-D array
random_choice = np.random.choice([1, 2, 3, 4, 5], size=(5, 2))
print("\nRandom choice:\n", random_choice)

# Generate a 5x2 array of random floats in [1.0, 3.0)
random_uniforms = np.random.uniform(1.0, 3.0, (5, 2))
print("\nRandom uniforms:\n", random_uniforms)

# Generate a 5x2 array of random samples from a binomial distribution
random_binomials = np.random.binomial(n=10, p=0.5, size=(5, 2))
print("\nRandom binomials:\n", random_binomials)

# Generate a 5x2 array of random samples from a beta distribution
random_betas = np.random.beta(a=2.0, b=5.0, size=(5, 2))
print("\nRandom betas:\n", random_betas)

# Generate a 5x2 array of random samples from a Poisson distribution
random_poissons = np.random.poisson(lam=3.0, size=(5, 2))
print("\nRandom poissons:\n", random_poissons)

Random floats:
 [[0.71246609 0.80566456]
 [0.38082273 0.34238953]
 [0.24984541 0.58954358]
 [0.00496489 0.74368192]
 [0.97718265 0.65398754]]

Random floats using rand:
 [[[0.83572326 0.22974362 0.74661799]
  [0.93108705 0.06056307 0.12830253]]

 [[0.04784606 0.73866871 0.51479765]
  [0.70044483 0.43128395 0.46939596]]

 [[0.44999137 0.63097927 0.87503673]
  [0.29986047 0.56852696 0.01896843]]

 [[0.16971007 0.03105836 0.39528227]
  [0.79169168 0.23012337 0.82164537]]

 [[0.03010594 0.2839017  0.76328972]
  [0.54353038 0.92558138 0.44756611]]]

Random normals:
 [[ 0.42853312 -1.41299521]
 [-1.42122652  0.32175166]
 [ 0.72138187 -0.75010339]
 [-1.02121887 -1.34944911]
 [ 1.68000152 -0.88270053]]

Random integers:
 [[0 7]
 [6 7]
 [1 8]
 [1 6]
 [9 1]]

Random choice:
 [[2 2]
 [3 2]
 [2 1]
 [2 3]
 [1 1]]

Random uniforms:
 [[1.76431636 2.06069527]
 [1.80744727 2.37975585]
 [2.14379988 1.3333361 ]
 [2.40019744 1.74879711]
 [1.04511606 2.13936076]]

Random binomials:
 [[6 6]
 [4 8]
 [3 9]
 [

In [139]:
normalized_data = (data - np.mean(data)) / np.std(data)
print("Normalized data : \n",normalized_data)

Normalized data : 
 [ 1.45971245  1.46046456 -1.3236788   0.99266905  0.15423254 -0.81752875
 -2.07297991  0.29227553 -0.9960098  -0.80689145  0.61343017 -1.13032897
 -0.04951962 -0.72093538  0.77094483  0.30035861 -0.01334582  1.75902319
  1.3856338  -0.47613446 -0.06800104  0.91059325  1.6205328  -1.13133687
  0.15196921 -0.68870185  0.73762733 -0.86135499 -0.55947728  0.61789153
 -0.74692655  1.60488304  0.72275033  0.84718314 -1.18531427  1.32198968
 -0.61278132  0.70102558 -0.48270559 -0.97818106  0.9691952   2.28263326
  0.98217915 -1.05775224  0.09953234 -0.05315678 -0.40269649 -1.13152185
 -0.19436373  0.52634072 -0.76260733  0.21682762 -2.12147043 -2.47444908
 -0.34114913 -0.54619123 -0.14017034  0.36804032  0.11164392  0.06072099
 -0.73939848 -0.69864174  0.77256074 -0.47439576  1.38397646 -1.08595902
 -1.58353108  0.4269761   1.08536782  0.43108051  0.57514111 -0.69661326
  0.91325466 -0.25293142  0.29095659 -1.17328363 -1.55170483 -0.48306753
  0.40105398  1.81947047  0.424

In [145]:
data = np.random.normal(size = 20 , loc = 50 , scale = 0.2) #loc = location parameter
print(data) 

[49.98308535 49.67023909 49.83479472 50.31041301 49.79744727 50.21381611
 50.24721505 50.15440713 49.81002109 49.98256786 50.02016329 49.64473137
 49.82765611 50.17193967 50.1409853  50.04949306 49.76484534 49.69942568
 50.36447016 49.56352398]


In [153]:
array = np.arange(21)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [159]:
even_mask = array % 2 == 0
even_numbers = array[even_mask]

print("Even Numbers ",even_numbers)

Even Numbers  [ 0  2  4  6  8 10 12 14 16 18 20]


In [171]:
arr = np.array([1.32473,23.34234,42.2342,3.23432])

rounded_array = np.round(arr,decimals = 2)

print(rounded_array)

arr = np.array([2.9 , -2.9 , 2.9 , -2.1])

fixed_arr = np.fix(arr)

print(fixed_arr)

[ 1.32 23.34 42.23  3.23]
[ 2. -2.  2. -2.]
